#!/usr/bin/env python3

import json
import os
import sys


#
# Global
#

CEPH_DIAGNOSTICS_COLLECT_DIR = os.environ.get('CEPH_DIAGNOSTICS_COLLECT_DIR')

cmd_description='check 2 or more pg replica/shards on the same host'

#
# Functions
#

def description():
    print(cmd_description)

def help():
    print(cmd_description)

def main():
    if len(sys.argv) > 1:
        if sys.argv[1] == 'description':
            description()
            exit(0)
        elif sys.argv[1] == 'help':
            help()
            exit(0)

    with open(os.path.join(CEPH_DIAGNOSTICS_COLLECT_DIR,
                           "osd_info-metadata"), "r") as f:
        osd_metadata = json.load(f)

    osds = {o['id'] : o['hostname'] for o in osd_metadata}

    with open(os.path.join(CEPH_DIAGNOSTICS_COLLECT_DIR,
                           "pg_info-dump_json"), "r") as f:
        pg_dump = json.load(f)

    exit_code = 0
    for pg in pg_dump['pg_map']['pg_stats']:
        hosts = {}
        for osd_id in pg['up']:
            h = osds[osd_id]
            if h in hosts:
                print(f"{pg['pgid']}: osd.{osd_id} and osd.{hosts[h]} are on the same host {host}")
                exit_code += 1
            else:
                hosts[h] = osd_id

    exit(exit_code)


#
# main
#

main()
