#!/bin/sh

CEPH_COPILOT="${CEPH_COPILOT:-copilot}"

description() {
    echo "run copilot command"
}

help() {
    description
    echo ""
    echo "supported commands:"
    echo ""
    echo "  checkup [-v|--verbose]"
    echo "  pg distribution [options]"
    echo ""
}

checkup() {
    eval ${CEPH_COPILOT} cluster checkup \
         --ceph_report_json="${CEPH_DIAGNOSTICS_COLLECT_DIR}/cluster_health-report" \
         "$@"
}

pg_distribution() {
    eval ${CEPH_COPILOT} pools pg distribution \
         --osd_tree_json="${CEPH_DIAGNOSTICS_COLLECT_DIR}/osd_info-tree_json" \
         --pg_dump_json="${CEPH_DIAGNOSTICS_COLLECT_DIR}/pg_info-dump_json" \
         "$@"
}

cmd="$@"

case "$cmd" in
    description)
        description
        exit 0
        ;;
    help)
        help
        exit 0
        ;;
    "-v"|"--verbose"|"checkup -v"|"checkup --verbose")
	checkup --verbose
        ;;
    ""|"checkup"*)
	checkup ${cmd#checkup}
        ;;
    "pg distribution"*)
	pg_distribution ${cmd#pg distribution}
	;;
    *)
	echo "invalid or unsupported copilot command: $cmd" >&2
        exit 1
        ;;
esac
