#!/bin/sh

CLYSO_FSA_DIR="${CLYSO_FSA_DIR:-$HOME/clyso/clyso-fsa}"
CLYSO_FSA_CUSTOMER="${CLYSO_FSA_CUSTOMER:-CLYSO FSA CUSTOMER}"

description() {
    echo "run fsa command"
}

help() {
    description
    echo ""
    echo "usage: fsa [customer name]"
    echo ""
}

fsa() {
    if [ ! -d "${CLYSO_FSA_DIR}/.venv" ]; then
        echo "cannot find fsa virtual environment ${CLYSO_FSA_DIR}/.venv" >&2
        echo "fsa is not installed or CLYSO_CCT_DIR is not set correctly" >&2
        exit 1
    fi

    local fsa_dir=$(mktemp -d)
    trap "rm -rf ${fsa_dir}" EXIT
    (cd ${fsa_dir} && ln -s "${CEPH_DIAGNOSTICS_COLLECT_DIR}")

    local customer="${CLYSO_FSA_CUSTOMER}"
    if [ -n "$1" ]; then
        customer="$*"
    fi

    cd ${CLYSO_FSA_DIR}
    source $HOME/clyso/clyso-fsa/.venv/bin/activate
    python3 generate_fsa.py --fsa-dir "${fsa_dir}" --customer "${customer}"
}

cmd="$@"

case "$cmd" in
    description)
        description
        exit 0
        ;;
    help)
        help
        exit 0
        ;;
    *)
	fsa ${cmd}
        ;;
esac
