#!/usr/bin/env python3

import argparse
import os
import re
import sys

from datetime import datetime

sys.path.append(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "lib"))
from common import json_load, handle_broken_pipe


#
# Global
#

CEPH_DIAGNOSTICS_COLLECT_DIR = os.environ.get('CEPH_DIAGNOSTICS_COLLECT_DIR')

cmd_description='print ceph daemon historic ops'

parser = argparse.ArgumentParser(prog='cds historic_ops', description=cmd_description)
parser.add_argument(
    'daemon',
    metavar='mds.x|mon.x|osd.x',
    help='print ops for this daemon',
    nargs='?',
    default=None,
)
parser.add_argument(
    '-d', '--sort-by-daemon',
    action='store_true',
    help='sort by daemon',
    default=False,
)
parser.add_argument(
    '-t', '--sort-by-duration',
    action='store_true',
    help='sort by duration',
    default=False,
)
parser.add_argument(
    '-r', '--correlate-subops',
    action='store_true',
    help='try to correlate osd ops with repops',
    default=False,
)
parser.add_argument(
    '-s', '--slow-ops',
    action='store_true',
    help='also process slow ops dumps',
    default=False,
)


#
# Functions
#

def description():
    print(cmd_description)

def help():
    parser.print_help()

def time_from_str(time_str):
    dt = datetime.strptime(time_str, '%Y-%m-%dT%H:%M:%S.%f%z')
    return dt.timestamp()

def get_longest_event_transition(op):
    longest= (None, 0)
    previous = None

    for e in op['type_data']['events']:
        t = e['time']
        if previous is None:
            longest = (f" -> {e['event']}", 0)
        else:
            d = time_from_str(t) - time_from_str(previous['time'])
            if d > longest[1]:
                longest = (f"{previous['event']} -> {e['event']}", d)
        previous = e

    return longest

def get_subops_info(op):
    for e in op['type_data']['events']:
        m = re.match(r'^waiting for subops from (.*)', e['event'])
        if not m:
            continue
        osds = [f'osd.{i}' for i in m.group(1).split(',')]
        return time_from_str(e['time']), osds

    return None, None

def get_subops(ops, primary, client, oid, sent_time, duration, osds):
    subops = {osd: None for osd in osds}

    for op in ops:
        if op['daemon'] not in osds:
            continue
        initiated_at = time_from_str(op['initiated_at'])
        if initiated_at < sent_time or initiated_at > sent_time + duration:
            continue
        m = re.match(
            r'^osd_repop\((osd\.\d+|client\.\d+)\.[^\s]+\s+[^\s]+\s+[^\s]+\s+([^\s]+)',
            op['description']
        )
        if not m:
            continue
        if m.group(1) not in (primary, client) or m.group(2) != oid:
            continue
        if not subops[op['daemon']] or \
           initiated_at < time_from_str(subops[op['daemon']]['initiated_at']):
            subops[op['daemon']] = op

    return subops

@handle_broken_pipe
def main():
    if len(sys.argv) > 1:
        if sys.argv[1] == 'description':
            description()
            exit(0)
        elif sys.argv[1] == 'help':
            help()
            exit(0)

    args = parser.parse_args()

    ops = []
    for fname in os.listdir(CEPH_DIAGNOSTICS_COLLECT_DIR):
        slow = 'slow_' if args.slow_ops else ''
        m = re.match(
            rf'^.*-(mds|mon|osd)\.(.+)[-_]dump_historic_({slow})?ops$',
            fname
        )
        if not m:
            continue
        daemon_type = m.group(1)
        daemon = f'{m.group(1)}.{m.group(2)}'
        if args.daemon and \
           args.daemon not in (daemon_type, f'{daemon_type}.*', daemon):
            continue
        historic_ops = json_load(
            os.path.join(CEPH_DIAGNOSTICS_COLLECT_DIR, fname),
            exit_on_error=False
        )
        if not historic_ops:
            continue
        ops_key = None
        for k in ('ops', 'Ops'):
            if k in historic_ops:
                ops_key = k
                break
        if not ops_key:
            print(f'Warning: no ops key found in {fname}, skipping', file=sys.stderr)
            continue
        ops.extend([dict({'daemon' : daemon}, **x) for x in historic_ops[ops_key]])

    if args.sort_by_duration:
        ops.sort(key=lambda op: op['duration'], reverse=True)

    if args.sort_by_daemon:
        ops.sort(key=lambda op: op['daemon'])

    try:
        for op in ops:
            name, duration = get_longest_event_transition(op)
            print('%-8s %1.3f %s [%s %1.3f] %s' % (op['daemon'],
                                                   op['duration'],
                                                   op['initiated_at'],
                                                   name, duration,
                                                   op['description']))
            if not args.correlate_subops or not op['daemon'].startswith('osd.'):
                continue
            m = re.match(r'^osd_op\((client\.\d+)\.[^\s]+\s+[^\s]+\s+([^\s]+)', op['description'])
            if not m:
                continue
            client= m.group(1)
            oid = m.group(2)
            sent_time, osds = get_subops_info(op)
            if not sent_time:
                continue
            subops = get_subops(ops, op['daemon'], client, oid, sent_time,
                                op['duration'], osds)
            for osd, op in subops.items():
                if not op:
                    print('  -> %-8s <NO MATCHING OP>' % (osd))
                    continue
                name, duration = get_longest_event_transition(op)
                print('  -> %-8s %1.3f %s [%s %1.3f] %s' % (op['daemon'],
                                                            op['duration'],
                                                            op['initiated_at'],
                                                            name, duration,
                                                            op['description']))
            sys.stdout.flush()
    except IOError as e:
        pass

#
# main
#

if __name__ == "__main__":
    main()
