#!/bin/sh

description() {
    echo "process pg dump"
}

help() {
    description
    echo
    echo "Commands: "
    echo "  ls-by-osd <id|osd.id>      - list pg on osd [osd]"
    echo "  ls-by-primary <id|osd.id>  - list pg with primary = [osd]"
    echo "  info <pgid>                - show pg info"
    echo "  stats <pgid>               - show pg stats in json format"
}

get_osd_id() {
    id=$(echo $1 | sed -s 's/osd\.//')
    case "${id}" in
        [0-9]*)
            echo ${id}
            ;;
        *)
            echo "invalid osd id: '$id'" >&2
            exit 1
            ;;
    esac
}

ls_by_osd() {
    local id
    local pgdump="${CEPH_DIAGNOSTICS_COLLECT_DIR}/pg_info-dump"
    local base=16

    id=$(get_osd_id $1) || exit 1

    grep -q LOG_DUPS "${pgdump}" && base=$((base+1))

    awk '
      $1 == "PG_STAT" || $1 ~ /^[0-9]+\./ && ($'${base}' ~ /[,\[]'${id}'[,\]]/ || $'$((base+2))' ~ /[,\[]'${id}'[,\]]/)
    ' "${pgdump}"
}

ls_by_primary() {
    local id
    local pgdump="${CEPH_DIAGNOSTICS_COLLECT_DIR}/pg_info-dump"
    local base=17

    id=$(get_osd_id $1) || exit 1

    grep -q LOG_DUPS "${pgdump}" && base=$((base+1))

    awk '
      $1 == "PG_STAT" || $1 ~ /^[0-9]+\./ && ('${base}' == '${id}' || $'$((base+2))' == '${id}')
    ' "${pgdump}"
}

info() {
    local pgid=$1

    stats ${pgid} | jq -r '. |
      ["pgid:      ", .pgid],
      ["state:     ", .state],
      ["up:        ", .up[]],
      ["acting:    ", .acting[]],
      ["objects:   ", .stat_sum.num_objects],
      ["bytes:     ", .stat_sum.num_bytes],
      ["omap_keys: ", .stat_sum.num_omap_keys],
      ["omap_bytes:", .stat_sum.num_omap_bytes],
      ["unfound:   ", .stat_sum.num_objects_unfound],
      ["snaptrimq: ", .snaptrimq_len],
      ["scrub:     ", .last_scrub_stamp],
      ["deep-scrub:", (.last_deep_scrub_stamp, "(" + (.last_scrub_duration | tostring) + " sec)")]
        | @tsv'
}

stats() {
    local pgid=$1
    local pgdump="${CEPH_DIAGNOSTICS_COLLECT_DIR}/pg_info-dump_json"

    jq ".pg_map.pg_stats[] | select(.pgid==\"${pgid}\")" < "${pgdump}"
}

scrub_stats() {
    local pgdump="${CEPH_DIAGNOSTICS_COLLECT_DIR}/pg_info-dump_json"

    if ! grep -q scrub_duration "${pgdump}"; then
	echo "no scrub stats in pg dump" >&2
	exit 1
    fi

    jq -r '.pg_map.pg_stats[] | (.pgid + " " + (.scrub_duration | tostring))' < "${pgdump}" |
    awk '{
      n++
      sum += $2
      pool = substr($1, 1, index($1, ".") - 1)
      num[pool]++
      sum_pool[pool] += $2
    }
    END {
	  print "total number of pgs: " n
	  print "total scrub duration: " sum " sec"
	  print "average scrub duration: " sum / n " sec"
	  print "per pool scrub duration:"
	  for (p in num) {
		print "  " p ": " sum_pool[p] " sec (" num[p] " pgs, " sum_pool[p] / num[p] " sec/pg)"
	  }
	}
    '
}

case "$1" in
    description)
        description
        exit 0
        ;;
    help)
        help
        exit 0
        ;;
    ls-by-osd|ls-by-primary|info|stats|scrub-stats)
        cmd="$(echo $1 | sed -e 's/-/_/g')"
        shift
        ${cmd} "$@"
        exit $?
        ;;
    *)
	echo "invalid command: '$1'" >&2
	echo "" >&2
        help >&2
        exit 1
        ;;
esac
